### PR TITLE
BlobPut: preserve the passed blob descriptor when doing chunked upload

### PR DESCRIPTION
**Pull request by edigaryev**
Problem: currently, the `BlobPut()` behaves inconsistently when doing a monolithic vs chunked upload. For monolithic upload, it preserves the passed blob descriptor on upload success and returns it as is, but for chunked upload it creates a new descriptor with only a few fields set.

Solution: make chunked upload code path behave similarly to the monolithic upload path w.r.t. blob descriptor manipulation.

### CODE REVIEW

**Review by sudo-bmitch — CHANGES_REQUESTED** [review]
This assumes the input descriptor is valid, where the BlobPut methods assume the size and digest it calculates on the reader for the pushed content are authoritative.

**Comment by edigaryev** [comment]
> This assumes the input descriptor is valid, where the BlobPut methods assume the size and digest it calculates on the reader for the pushed content are authoritative.

But the monolithic upload code path already assumes that, and returns the descriptor unchanged.

It's a pretty weird behavior where you upload almost identical blobs, but of different size, and you get your descriptor back intact in one case, and in the other case it is mangled by the `blobPutUploadChunked()`.

Would patching the the `Digest` field of the descriptor returned from`blobPutUploadChunked()` work for you?

**Comment by sudo-bmitch** [comment]
I think it would make sense for both of these methods to validate the descriptor. That's often done by the registry in the monolithic upload  and we can repeat that on the client. For the chunked upload, that validation would need to be skipped if the zero value is encountered.

**Comment by sudo-bmitch** [comment]
This was fixed in #637 with some validation improvements and better handling for the zero length blob. Thanks for the report and suggestion!

**Pull request closed without merging**
